add_requires("tbb", "mkl")

target("libvlm")
    set_kind("static")
    add_packages("tbb", "mkl")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})

target("vlm")
    set_kind("binary")
    set_default(true)
    add_deps("libvlm")
    set_runargs({"-i"}, {"../../../../config/elliptic.vlm"}, {"-m"}, {"../../../../mesh/elliptic_64x64.xyz"}, {"-o"}, {"../../../../results/elliptic.vtu"})
    add_files("dev/main.cpp")

target("vlm-tests")
    set_kind("binary")
    set_default(false)
    add_deps("libvlm")
    add_files("dev/tests.cpp")