add_requires("cuda", {configs={utils={"cublas", "cusolver"}}})
add_requires("taskflow_custom")

target("backend-cuda")
    set_kind("static")
    set_default(false)
    add_packages("cuda")
    add_packages("taskflow_custom")
    add_includedirs("../../include")
    add_files("src/*.cu")
    add_includedirs("include", {public = true})
