name: linux-gpu3
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/linux_gpu3.yaml'
      - 'README.md'

jobs:
  build:
    runs-on: 
      - runs-on
      - runner=gpu-nvidia-rtx
      - run-id=${{ github.run_id }}
    env: 
      CACHE_PATH:
      CACHE_KEY:

    strategy:
      matrix:
        arch: [x86_64]
        mode: [release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SMI
        run: nvidia-smi