name: linux
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/linux.yaml'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env: 
      CACHE_PATH:
      CACHE_KEY:

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        mode: [release, debug]
        compiler: [clang, gcc]
        sanitizer: [address, undefined] # thread removed due to bugs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ISPC
        run: |
          curl -L "https://github.com/ispc/ispc/releases/download/v1.22.0/ispc-v1.22.0-linux.tar.gz" -o ispc.tar.gz
          tar -xzf ispc.tar.gz
          echo "${PWD}/ispc-v1.22.0-linux/bin" >> $GITHUB_PATH

      # Install system dependencies (opengl)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev clang libomp-dev libc++-dev gcc g++ gobjc

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      # Install xmake
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: .xmake-cache

      # Update xmake repository
      - name: Update xmake repository
        run: xmake repo --update

      # Create xmake dependencies hash
      - name: Retrieve dependencies hash
        id: dep_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT

      - name: Set cache env vars
        run: |
          echo "CACHE_PATH=${{ env.XMAKE_GLOBALDIR }}/.xmake/packages" >> $GITHUB_ENV
          echo "CACHE_KEY=Linux-${{ matrix.compiler }}-${{ matrix.arch }}-${{ matrix.mode }}-${{ matrix.sanitizer }}-${{ steps.dep_hash.outputs.hash }}" >> $GITHUB_ENV

      # Cache xmake dependencies
      - name: Restore cached xmake dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}

      # Config xmake
      - name: Config
        run: |
          xmake f -vD -y -a ${{ matrix.arch }} -m ${{ matrix.mode }} --toolchain=${{ matrix.compiler }} --policies=build.sanitizer.${{ matrix.sanitizer }}

      - name: Cache xmake dependencies
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}
          
      # Build
      - name: Build
        run: |
          xmake -vD

      - name: Test
        run: |
          xmake test -j1 -v
